version: "1"
# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
  co: pr checkout
  release list-in: '!GH_REPO=$(gh search repos "${1}" -q .[0].fullName --json fullName) gh release list'
  release view-in: '!GH_REPO=$(gh search repos "${1}" -q .[0].fullName --json fullName) gh release view "${2}"'
  release install: '!GH_REPO=$(gh search repos "${1}" -q .[0].fullName --json fullName); GH_TAG=$(gh release view -R "${GH_REPO}" --jq .tagName --json tagName "${2}"); GH_DIR="${3:-${HOME}/.gh/bin}"; echo "gh-release-install --repo \"${GH_REPO}\" --tag \"${GH_TAG}\" --dir \"${GH_DIR}\""; gh-release-install --repo "${GH_REPO}" --tag "${GH_TAG}" --dir "${GH_DIR}"'
  ratelimit: api /rate_limit
  annotations: "!gh api /repos/${1}/actions/workflows --paginate -q .workflows[].url | xargs -I{URL} gh api {URL}/runs?per_page=${2:-1} -q .workflow_runs[].jobs_url | xargs -I{JOBS_URL} gh api {JOBS_URL} --paginate -q .jobs[].check_run_url | xargs -I{CHECK_RUN_URL} gh api {CHECK_RUN_URL}/annotations --paginate"
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
