alias diff="diff -u -N --color=auto"
alias k="kubectl"
alias kw="watch kubectl"
alias ll="ls -l"
alias marp="docker run --rm --init -v \"${PWD}:/home/marp/app\" -e \"LANG=${LANG}\" -e MARP_USER=\"$(id -u):$(id -g)\" -p 8080:8080 -p 37717:37717 marpteam/marp-cli -s ."
