#!/bin/bash

set -eo pipefail

if [ "${1}" = "docker-cli-plugin-metadata" ]; then
    echo '{"SchemaVersion": "0.1.0","Vendor": "shibataka000","Version": "v0.1.0","ShortDescription": "Delete all docker containers and images"}'
    exit
fi

if [ -n "$(docker ps -aq)" ];  then
    docker ps -aq | xargs docker rm
fi

if [ -n "$(docker images -aq)" ]; then
    docker images -aq | xargs docker rmi
fi
